version: '3'

networks:
    laravel:

services:
    app:
        image: bungamungil/devtools:0.2
        container_name: app
        tty: true
        ports:
            - "8000:8000"
        volumes:
            - .:/app
        depends_on:
            - mysql
        networks:
            - laravel
        stdin_open: true
        environment:
            APP_KEY: base64:RWTMyzHxmPOVeQr/Phs/9SnVPR95lSSO4qLZU0fHf6I=
            APP_ENV: local
            APP_DEBUG: "true"
            DB_CONNECTION: mysql
            DB_HOST: mysql
            DB_PORT: 3306
            DB_DATABASE: psi
            DB_USERNAME: root
            DB_PASSWORD: password
        working_dir: /app
        entrypoint: ['php', '/app/artisan', 'serve', '--host', '0.0.0.0']

    mysql:
        image: mysql:latest
        container_name: mysql
        tty: true
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: password
        volumes:
            - ./storage/rawdb:/var/lib/mysql
        networks:
            - laravel
